[theme]
primaryColor             = "#104F3A"
backgroundColor          = "#F5EFE0"
secondaryBackgroundColor = "#EDE6D3"
textColor                = "#1F2A24"
font                     = "sans serif"

[server]
headless         = false
port             = 8501

[browser]
gatherUsageStats = false
