[theme]
primaryColor             = "#9ACD32"
backgroundColor          = "#0D1F14"
secondaryBackgroundColor = "#142B1C"
textColor                = "#F5EFE0"
font                     = "sans serif"

[server]
headless         = false
port             = 8501

[browser]
gatherUsageStats = false
